"""Add Agent model with AgentId field

Revision ID: 07bc602e08fc
Revises: 109654ab3d43
Create Date: 2025-10-18 16:28:48.759953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bc602e08fc'
down_revision: Union[str, Sequence[str], None] = '109654ab3d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('AgentId', sa.String(), nullable=False))
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.create_index(op.f('ix_agents_AgentId'), 'agents', ['AgentId'], unique=False)
    op.drop_column('agents', 'id')
    op.add_column('chat_sessions', sa.Column('agent_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'agents', ['agent_id'], ['AgentId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'agent_id')
    op.add_column('agents', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_agents_AgentId'), table_name='agents')
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.drop_column('agents', 'AgentId')
    # ### end Alembic commands ###
