"""Remove is_active from llm_providers and llm_models

Revision ID: 109654ab3d43
Revises: 10fd4983102a
Create Date: 2025-10-17 15:34:27.846257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109654ab3d43'
down_revision: Union[str, Sequence[str], None] = '10fd4983102a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_models', 'input_cost_per_token')
    op.drop_column('llm_models', 'output_cost_per_token')
    op.drop_column('llm_models', 'is_active')
    op.drop_column('llm_providers', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('llm_models', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('llm_models', sa.Column('output_cost_per_token', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('llm_models', sa.Column('input_cost_per_token', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
