"""add_user_secrets_table

Revision ID: 7dde0fdd5485
Revises: bbfef7e9d726
Create Date: 2025-10-21 15:20:04.018128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dde0fdd5485'
down_revision: Union[str, Sequence[str], None] = 'bbfef7e9d726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_secrets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('secret_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_secrets_id'), 'user_secrets', ['id'], unique=False)
    op.create_index(op.f('ix_user_secrets_user_id'), 'user_secrets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_secrets_user_id'), table_name='user_secrets')
    op.drop_index(op.f('ix_user_secrets_id'), table_name='user_secrets')
    op.drop_table('user_secrets')
    # ### end Alembic commands ###
