"""add_rag_knowledge_base_and_refactor_agent_tools

Revision ID: 90ec662a6c0a
Revises: 7dde0fdd5485
Create Date: 2025-12-02 00:25:21.374679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90ec662a6c0a'
down_revision: Union[str, Sequence[str], None] = '7dde0fdd5485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configured_tools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tool_type', sa.String(), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configured_tools_id'), 'configured_tools', ['id'], unique=False)
    op.create_index(op.f('ix_configured_tools_user_id'), 'configured_tools', ['user_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vector_db', sa.String(), nullable=False),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('use_ocr', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_user_id'), 'knowledge_bases', ['user_id'], unique=False)
    op.create_table('agent_tool_association',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('tool_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.AgentId'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['configured_tools.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    op.create_table('sandboxes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('e2b_sandbox_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.AgentId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandboxes_agent_id'), 'sandboxes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_sandboxes_e2b_sandbox_id'), 'sandboxes', ['e2b_sandbox_id'], unique=True)
    op.create_index(op.f('ix_sandboxes_id'), 'sandboxes', ['id'], unique=False)
    op.create_index(op.f('ix_sandboxes_state'), 'sandboxes', ['state'], unique=False)
    op.create_index(op.f('ix_sandboxes_user_id'), 'sandboxes', ['user_id'], unique=False)
    op.create_table('sandbox_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sandbox_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_events_id'), 'sandbox_events', ['id'], unique=False)
    op.create_index(op.f('ix_sandbox_events_sandbox_id'), 'sandbox_events', ['sandbox_id'], unique=False)
    op.create_index(op.f('ix_sandbox_events_timestamp'), 'sandbox_events', ['timestamp'], unique=False)
    op.create_table('sandbox_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sandbox_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_used_pct', sa.Float(), nullable=False),
    sa.Column('mem_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mem_total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('disk_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('disk_total_bytes', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_metrics_id'), 'sandbox_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_sandbox_metrics_sandbox_id'), 'sandbox_metrics', ['sandbox_id'], unique=False)
    op.create_index(op.f('ix_sandbox_metrics_timestamp'), 'sandbox_metrics', ['timestamp'], unique=False)
    op.drop_column('agents', 'tools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('tools', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sandbox_metrics_timestamp'), table_name='sandbox_metrics')
    op.drop_index(op.f('ix_sandbox_metrics_sandbox_id'), table_name='sandbox_metrics')
    op.drop_index(op.f('ix_sandbox_metrics_id'), table_name='sandbox_metrics')
    op.drop_table('sandbox_metrics')
    op.drop_index(op.f('ix_sandbox_events_timestamp'), table_name='sandbox_events')
    op.drop_index(op.f('ix_sandbox_events_sandbox_id'), table_name='sandbox_events')
    op.drop_index(op.f('ix_sandbox_events_id'), table_name='sandbox_events')
    op.drop_table('sandbox_events')
    op.drop_index(op.f('ix_sandboxes_user_id'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_state'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_id'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_e2b_sandbox_id'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_agent_id'), table_name='sandboxes')
    op.drop_table('sandboxes')
    op.drop_table('agent_tool_association')
    op.drop_index(op.f('ix_knowledge_bases_user_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_configured_tools_user_id'), table_name='configured_tools')
    op.drop_index(op.f('ix_configured_tools_id'), table_name='configured_tools')
    op.drop_table('configured_tools')
    # ### end Alembic commands ###
